# Generated by Django 4.0.5 on 2022-06-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('realisateur', models.CharField(max_length=100)),
                ('date_parution', models.DateField(blank=True, null=True)),
                ('dure', models.IntegerField()),
                ('cat', models.CharField(choices=[('Action', 'Action'), ('Animation', 'Animation'), ('Aventure', 'Aventure'), ('Horreur', 'Horreur'), ('Fantastique', 'Fantastique'), ('Science Fiction', 'Science Fiction'), ('Guerre', 'Guerre')], max_length=30)),
                ('resume', models.TextField(blank=True, null=True)),
                ('imaurl', models.URLField(max_length=300)),
            ],
        ),
    ]
