# Generated by Django 4.0.5 on 2022-06-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='absence',
            old_name='realisateur',
            new_name='cours',
        ),
        migrations.RenameField(
            model_name='absence',
            old_name='titre',
            new_name='etudiant',
        ),
        migrations.RemoveField(
            model_name='absence',
            name='date_parution',
        ),
        migrations.RemoveField(
            model_name='absence',
            name='dure',
        ),
        migrations.RemoveField(
            model_name='absence',
            name='resume',
        ),
        migrations.AlterField(
            model_name='absence',
            name='cat',
            field=models.CharField(choices=[('Justifié', 'Justifié'), ('Non Justifié', 'Non Justifié')], max_length=30),
        ),
    ]
