# Generated by Django 4.0.5 on 2022-06-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0002_rename_realisateur_absence_cours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='photo',
            field=models.FileField(default=255, upload_to='photo'),
            preserve_default=False,
        ),
    ]
