# Generated by Django 4.0.5 on 2022-06-09 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0005_remove_absence_imaurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='just',
            field=models.CharField(default=255, max_length=100),
            preserve_default=False,
        ),
    ]
