# Generated by Django 4.0.5 on 2022-06-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0006_absence_just'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('duree', models.IntegerField()),
                ('enseignant', models.CharField(max_length=100)),
                ('classe', models.CharField(choices=[('RT111', 'RT111'), ('RT112', 'RT112'), ('RT121', 'RT122'), ('RT131', 'RT132')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('group', models.CharField(choices=[('RT111', 'RT111'), ('RT112', 'RT112'), ('RT121', 'RT122'), ('RT131', 'RT132')], max_length=30)),
                ('photo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(choices=[('RT111', 'RT111'), ('RT112', 'RT112'), ('RT121', 'RT122'), ('RT131', 'RT132')], max_length=30)),
            ],
        ),
    ]
