# Generated by Django 4.0.5 on 2022-06-09 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0007_cours_enseignant_etudiant_groupe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Groupe',
            new_name='Groupetu',
        ),
    ]
