-- MySQL Script generated by MySQL Workbench
-- Sun Jun 12 20:41:05 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET latin1 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Groupes étudiants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Groupes étudiants` (
  `id Groupes étudiants` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NULL,
  PRIMARY KEY (`id Groupes étudiants`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Etudiants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Etudiants` (
  `id Etudiants` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NULL,
  `Prénom` VARCHAR(45) NULL,
  `Email` VARCHAR(144) NULL,
  `Groupe` INT NULL,
  `Photo` LONGTEXT NULL,
  PRIMARY KEY (`id Etudiants`),
  INDEX `Groupe` (`Groupe` ASC) VISIBLE,
  CONSTRAINT `Groupe`
    FOREIGN KEY (`Groupe`)
    REFERENCES `mydb`.`Groupes étudiants` (`id Groupes étudiants`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Enseignants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Enseignants` (
  `id Enseignants` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NULL,
  `Prénom` VARCHAR(45) NULL,
  `Email` VARCHAR(144) NULL,
  PRIMARY KEY (`id Enseignants`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cours`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cours` (
  `id Cours` INT NOT NULL AUTO_INCREMENT,
  `Titre cours` VARCHAR(100) NULL,
  `Date` DATETIME NULL,
  `Enseignant` INT NULL,
  `Durée` TIME NULL,
  `Groupe` INT NULL,
  PRIMARY KEY (`id Cours`),
  INDEX `Enseignant` (`Enseignant` ASC) VISIBLE,
  INDEX `groupe` (`Groupe` ASC) VISIBLE,
  CONSTRAINT `Enseignant`
    FOREIGN KEY (`Enseignant`)
    REFERENCES `mydb`.`Enseignants` (`id Enseignants`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `groupe`
    FOREIGN KEY (`Groupe`)
    REFERENCES `mydb`.`Groupes étudiants` (`id Groupes étudiants`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Absences`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Absences` (
  `id Absences` INT NOT NULL AUTO_INCREMENT,
  `Etudiant` INT NULL,
  `Cours` INT NULL,
  `Justifié ?` TINYINT(1) NULL,
  `Justification` LONGTEXT NULL,
  PRIMARY KEY (`id Absences`),
  INDEX `Etudiant` (`Etudiant` ASC) VISIBLE,
  INDEX `cours` (`Cours` ASC) VISIBLE,
  CONSTRAINT `Etudiant`
    FOREIGN KEY (`Etudiant`)
    REFERENCES `mydb`.`Etudiants` (`id Etudiants`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cours`
    FOREIGN KEY (`Cours`)
    REFERENCES `mydb`.`Cours` (`id Cours`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
