-- MySQL Script generated by MySQL Workbench
-- Mon Jun 13 20:58:23 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Groupes-etudiant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Groupes-etudiant` (
  `idGroupes-etudiant` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NULL,
  PRIMARY KEY (`idGroupes-etudiant`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Etudiants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Etudiants` (
  `idEtudiants` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NULL,
  `Prenom` VARCHAR(45) NULL,
  `Email` VARCHAR(144) NULL,
  `Photo` LONGTEXT NULL,
  `groupes` INT NOT NULL,
  PRIMARY KEY (`idEtudiants`, `groupes`),
  INDEX `group_idx` (`groupes` ASC) INVISIBLE,
  CONSTRAINT `group`
    FOREIGN KEY (`groupes`)
    REFERENCES `mydb`.`Groupes-etudiant` (`idGroupes-etudiant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Enseignants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Enseignants` (
  `idEnseignants` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NULL,
  PRIMARY KEY (`idEnseignants`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cours`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cours` (
  `idCours` INT NOT NULL AUTO_INCREMENT,
  `titre cours` VARCHAR(100) NULL,
  `Date` DATETIME NULL,
  `enseignant` INT NOT NULL,
  `Durée` TIME NULL,
  `Groupe` INT NOT NULL,
  PRIMARY KEY (`idCours`, `Groupe`, `enseignant`),
  INDEX `enseignant_idx` (`enseignant` ASC) VISIBLE,
  INDEX `group_idx` (`Groupe` ASC) VISIBLE,
  CONSTRAINT `enseignant`
    FOREIGN KEY (`enseignant`)
    REFERENCES `mydb`.`Enseignants` (`idEnseignants`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `group`
    FOREIGN KEY (`Groupe`)
    REFERENCES `mydb`.`Groupes-etudiant` (`idGroupes-etudiant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`absences`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`absences` (
  `idabsences` INT NOT NULL,
  `Etudiant` INT NOT NULL,
  `Cours` INT NOT NULL,
  `justification` LONGTEXT NULL,
  `justifie` SET('oui', 'non') NULL,
  PRIMARY KEY (`idabsences`, `Etudiant`, `Cours`),
  INDEX `etudiant_idx` (`Etudiant` ASC) VISIBLE,
  INDEX `cours_idx` (`Cours` ASC) VISIBLE,
  CONSTRAINT `etudiant`
    FOREIGN KEY (`Etudiant`)
    REFERENCES `mydb`.`Etudiants` (`idEtudiants`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cours`
    FOREIGN KEY (`Cours`)
    REFERENCES `mydb`.`Cours` (`idCours`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
